In [12]:
import pandas as pd

print("Python + Pandas funcionando correctamente")

Python + Pandas funcionando correctamente

In [13]:
from pathlib import Path

DATA_PATH = Path("../data/raw")

ventas = pd.read_csv(DATA_PATH / "Ventas.csv")
devoluciones = pd.read_csv(DATA_PATH / "Devoluciones.csv")
precios = pd.read_csv(DATA_PATH / "Precios.csv")
costos = pd.read_csv(DATA_PATH / "Costos.csv", sep=";")
objetivos = pd.read_csv(DATA_PATH / "Objetivos.csv")

print("Archivos cargados correctamente")

Archivos cargados correctamente

In [14]:
print(costos.columns.tolist())
print(costos.head())

['Periodo', 'ID_Producto', 'Costo_Unitario']
   Periodo  ID_Producto Costo_Unitario
0  2024-01            1         279,81
1  2024-02            1         278,76
2  2024-03            1         276,98
3  2024-04            1         278,67
4  2024-05            1         276,59

In [15]:
print("VENTAS:", ventas.shape)
print("DEVOLUCIONES:", devoluciones.shape)
print("PRECIOS:", precios.shape)
print("COSTOS:", costos.shape)
print("OBJETIVOS:", objetivos.shape)

VENTAS: (80536, 17)
DEVOLUCIONES: (4715, 15)
PRECIOS: (641, 3)
COSTOS: (2424, 3)
OBJETIVOS: (246, 3)

In [16]:
print("=== VENTAS ===")
print(ventas.columns.tolist())

print("\n=== DEVOLUCIONES ===")
print(devoluciones.columns.tolist())

print("\n=== PRECIOS ===")
print(precios.columns.tolist())

print("\n=== COSTOS ===")
print(costos.columns.tolist())

print("\n=== OBJETIVOS ===")
print(objetivos.columns.tolist())

=== VENTAS ===
['ID_Venta', 'ID_Pedido', 'Fecha', 'ID_Producto', 'ID_Cliente', 'ID_Tienda', 'Cantidad', 'Precio_Unitario', 'Canal_Venta', 'Categoría_Venta', 'Nombre_Cliente', 'Ubicación_Cliente', 'Nombre_Tienda', 'Ubicación_Tienda', 'Nombre_Producto', 'Categoría_Producto', 'Subcategoría_Producto']

=== DEVOLUCIONES ===
['ID_Devolución', 'ID_Venta', 'Fecha', 'ID_Producto', 'ID_Cliente', 'ID_Tienda', 'Cantidad_Devuelta', 'Motivo', 'Precio_Unitario', 'Nombre_Cliente', 'Ubicación_Cliente', 'Nombre_Tienda', 'Ubicación_Tienda', 'Nombre_Producto', 'Categoría_Producto']

=== PRECIOS ===
['ID_Producto', 'Vigencia_Desde', 'Precio_Lista']

=== COSTOS ===
['Periodo', 'ID_Producto', 'Costo_Unitario']

=== OBJETIVOS ===
['Periodo', 'ID_Tienda', 'Objetivo_Ventas']

In [18]:
tablas = {
    "Ventas": ventas,
    "Devoluciones": devoluciones,
    "Precios": precios,
    "Costos": costos,
    "Objetivos": objetivos
}

for nombre, df in tablas.items():
    print(f"\n{'='*50}")
    print(nombre)
    print(f"{'='*50}")
    print("\nTipos de datos:")
    print(df.dtypes)
    print("\nValores nulos:")
    print(df.isna().sum())

==================================================
Ventas
==================================================

Tipos de datos:
ID_Venta                   int64
ID_Pedido                  int64
Fecha                        str
ID_Producto                int64
ID_Cliente                 int64
ID_Tienda                  int64
Cantidad                   int64
Precio_Unitario          float64
Canal_Venta                  str
Categoría_Venta              str
Nombre_Cliente               str
Ubicación_Cliente            str
Nombre_Tienda                str
Ubicación_Tienda             str
Nombre_Producto              str
Categoría_Producto           str
Subcategoría_Producto        str
dtype: object

Valores nulos:
ID_Venta                   0
ID_Pedido                  0
Fecha                      0
ID_Producto                0
ID_Cliente                 0
ID_Tienda                  0
Cantidad                   0
Precio_Unitario            0
Canal_Venta              340
Categoría_Venta            0
Nombre_Cliente             0
Ubicación_Cliente          0
Nombre_Tienda              0
Ubicación_Tienda           0
Nombre_Producto            0
Categoría_Producto         0
Subcategoría_Producto      0
dtype: int64

==================================================
Devoluciones
==================================================

Tipos de datos:
ID_Devolución           int64
ID_Venta                int64
Fecha                     str
ID_Producto             int64
ID_Cliente              int64
ID_Tienda               int64
Cantidad_Devuelta       int64
Motivo                    str
Precio_Unitario       float64
Nombre_Cliente            str
Ubicación_Cliente         str
Nombre_Tienda             str
Ubicación_Tienda          str
Nombre_Producto           str
Categoría_Producto        str
dtype: object

Valores nulos:
ID_Devolución         0
ID_Venta              0
Fecha                 0
ID_Producto           0
ID_Cliente            0
ID_Tienda             0
Cantidad_Devuelta     0
Motivo                0
Precio_Unitario       0
Nombre_Cliente        0
Ubicación_Cliente     0
Nombre_Tienda         0
Ubicación_Tienda      0
Nombre_Producto       0
Categoría_Producto    0
dtype: int64

==================================================
Precios
==================================================

Tipos de datos:
ID_Producto         int64
Vigencia_Desde        str
Precio_Lista      float64
dtype: object

Valores nulos:
ID_Producto       0
Vigencia_Desde    0
Precio_Lista      0
dtype: int64

==================================================
Costos
==================================================

Tipos de datos:
Periodo             str
ID_Producto       int64
Costo_Unitario      str
dtype: object

Valores nulos:
Periodo           0
ID_Producto       0
Costo_Unitario    0
dtype: int64

==================================================
Objetivos
==================================================

Tipos de datos:
Periodo                str
ID_Tienda            int64
Objetivo_Ventas    float64
dtype: object

Valores nulos:
Periodo            0
ID_Tienda          0
Objetivo_Ventas    0
dtype: int64

In [19]:
for nombre, df in tablas.items():
    nulos = df.isna().sum()
    nulos = nulos[nulos > 0]

    print(f"\n=== {nombre} ===")

    if len(nulos) == 0:
        print("Sin valores nulos")
    else:
        print(nulos)

=== Ventas ===
Canal_Venta    340
dtype: int64

=== Devoluciones ===
Sin valores nulos

=== Precios ===
Sin valores nulos

=== Costos ===
Sin valores nulos

=== Objetivos ===
Sin valores nulos

In [20]:
ventas["Canal_Venta"].value_counts(dropna=False)

Canal_Venta
Offline    54247
Online     25949
NaN          340
Name: count, dtype: int64

In [21]:
# Revisar registros duplicados en Ventas

print("Filas totales:", len(ventas))
print("ID_Venta únicos:", ventas["ID_Venta"].nunique())
print("Duplicados de ID_Venta:", ventas["ID_Venta"].duplicated().sum())

Filas totales: 80536
ID_Venta únicos: 80295
Duplicados de ID_Venta: 241

In [22]:
# Ver algunos ID_Venta duplicados

duplicados = ventas[ventas["ID_Venta"].duplicated(keep=False)].sort_values("ID_Venta")

duplicados.head(20)

,ID_Venta,ID_Pedido,Fecha,ID_Producto,ID_Cliente,ID_Tienda,Cantidad,Precio_Unitario,Canal_Venta,Categoría_Venta,Nombre_Cliente,Ubicación_Cliente,Nombre_Tienda,Ubicación_Tienda,Nombre_Producto,Categoría_Producto,Subcategoría_Producto
1086,1087,525,2024-01-14,75,608,8,10,17.53,Offline,Wholesale,Importadora Santos Premium,Brazil,São Paulo Paulista,Brazil,Billetera,Ropa,Accesorios Moda
1087,1087,525,2024-01-14,75,608,8,10,17.53,Offline,Wholesale,Importadora Santos Premium,Brazil,São Paulo Paulista,Brazil,Billetera,Ropa,Accesorios Moda
1328,1328,642,2024-01-18,5,514,5,5,748.77,Offline,Wholesale,Mayorista Costa del Norte,México,Puebla Angelópolis,México,"Smart TV 75""",Electrónica,Televisores
1329,1328,642,2024-01-18,5,514,5,5,748.77,Offline,Wholesale,Mayorista Costa del Norte,México,Puebla Angelópolis,México,"Smart TV 75""",Electrónica,Televisores
1782,1781,857,2024-01-23,52,302,18,2,67.90,Offline,Retail,Ana Silva (302),Italy,Napoli Toledo,Italia,Vestido,Ropa,Mujer
1783,1781,857,2024-01-23,52,302,18,2,67.90,Offline,Retail,Ana Silva (302),Italy,Napoli Toledo,Italia,Vestido,Ropa,Mujer
1960,1958,945,2024-01-26,55,514,1,23,53.97,Offline,Wholesale,Mayorista Costa del Norte,México,CDMX Polanco,México,Blusa,Ropa,Mujer
1961,1958,945,2024-01-26,55,514,1,23,53.97,Offline,Wholesale,Mayorista Costa del Norte,México,CDMX Polanco,México,Blusa,Ropa,Mujer
2469,2466,1194,2024-02-01,15,402,11,2,74.35,Offline,Wholesale,Grupo Costa Premium (402),Brazil,Belo Horizonte Savassi,brasil,Auriculares Gamer,Electrónica,Audio
2470,2466,1194,2024-02-01,15,402,11,2,74.35,Offline,Wholesale,Grupo Costa Premium (402),Brazil,Belo Horizonte Savassi,brasil,Auriculares Gamer,Electrónica,Audio
2801,2797,1352,2024-02-05,17,301,12,2,347.33,Offline,Wholesale,Almacenes Souza del Norte,Brasil,Porto Alegre Moinhos,Brasil,Smartphone Gama Media,Electrónica,Telefonía
2802,2797,1352,2024-02-05,17,301,12,2,347.33,Offline,Wholesale,Almacenes Souza del Norte,Brasil,Porto Alegre Moinhos,Brasil,Smartphone Gama Media,Electrónica,Telefonía
2830,2825,1365,2024-02-06,89,12,1,61,5.75,Offline,Wholesale,Importadora Russo Express,México,CDMX Polanco,MEXICO,Galletitas,Alimentos,Snacks
2831,2825,1365,2024-02-06,89,12,1,61,5.75,Offline,Wholesale,Importadora Russo Express,México,CDMX Polanco,MEXICO,Galletitas,Alimentos,Snacks
3720,3714,1782,2024-02-17,85,608,8,109,9.03,Offline,Wholesale,Importadora Santos Premium,Brasil,São Paulo Paulista,Brasil,Vino Tinto,Alimentos,Bebidas
3721,3714,1782,2024-02-17,85,608,8,109,9.03,Offline,Wholesale,Importadora Santos Premium,Brasil,São Paulo Paulista,Brasil,Vino Tinto,Alimentos,Bebidas
4010,4003,1914,2024-02-21,78,196,2,4,6.00,Offline,Retail,Pedro Oliveira (196),México,CDMX Santa Fe,Mexico,Arroz 1kg,Alimentos,Almacén
4011,4003,1914,2024-02-21,78,196,2,4,6.00,Offline,Retail,Pedro Oliveira (196),México,CDMX Santa Fe,Mexico,Arroz 1kg,Alimentos,Almacén
4298,4290,2046,2024-02-24,55,529,8,2,60.66,Offline,Retail,Sofía Pereira (529),Brazil,São Paulo Paulista,Brasil,Blusa,Ropa,Mujer
4299,4290,2046,2024-02-24,55,529,8,2,60.66,Offline,Retail,Sofía Pereira (529),Brazil,São Paulo Paulista,Brasil,Blusa,Ropa,Mujer

In [23]:
# Cuantificar duplicados exactos en Ventas

duplicados_exactos = ventas[ventas.duplicated(keep=False)]

print("Registros involucrados en duplicados:", len(duplicados_exactos))
print("Filas duplicadas a eliminar:", ventas.duplicated().sum())
print("Filas originales:", len(ventas))
print("Filas después de eliminar duplicados:", len(ventas.drop_duplicates()))

Registros involucrados en duplicados: 482
Filas duplicadas a eliminar: 241
Filas originales: 80536
Filas después de eliminar duplicados: 80295

In [24]:
print("=== PAÍSES CLIENTE ===")
print(ventas["Ubicación_Cliente"].value_counts(dropna=False))

print("\n=== PAÍSES TIENDA ===")
print(ventas["Ubicación_Tienda"].value_counts(dropna=False))

=== PAÍSES CLIENTE ===
Ubicación_Cliente
Brasil     23260
México     23167
Italia     11641
Brazil      5630
Mexico      5026
MEXICO      3373
Italy       3259
brasil      2212
 México     1623
ITALIA      1345
Name: count, dtype: int64

=== PAÍSES TIENDA ===
Ubicación_Tienda
Brasil     23308
México     23254
Italia     11620
Brazil      5606
Mexico      4947
Italy       3297
MEXICO      3252
brasil      2188
 México     1736
ITALIA      1328
Name: count, dtype: int64

In [25]:
print("=== CATEGORÍAS DE PRODUCTO ===")
print(ventas["Categoría_Producto"].value_counts(dropna=False))

print("\n=== SUBCATEGORÍAS DE PRODUCTO ===")
print(ventas["Subcategoría_Producto"].value_counts(dropna=False))

print("\n=== CATEGORÍAS DE VENTA ===")
print(ventas["Categoría_Venta"].value_counts(dropna=False))

=== CATEGORÍAS DE PRODUCTO ===
Categoría_Producto
Ropa            28027
Alimentos       24107
Electrónica     17032
Muebles          8984
ropa              446
Ropa              413
Alimentos         367
alimentos         338
Electrónica       185
Electronica       171
electrónica       167
Muebles           154
muebles           145
Name: count, dtype: int64

=== SUBCATEGORÍAS DE PRODUCTO ===
Subcategoría_Producto
Accesorios Moda    6876
Almacén            6325
Calzado            6136
Mujer              5917
Niños              5797
Snacks             5790
Televisores        5701
Living             4646
Limpieza           4507
Frescos            4250
Hombre             4160
Bebidas            3940
Telefonía          3667
Computación        2961
Audio              2947
Accesorios         2279
Exterior           1904
Oficina            1585
Dormitorio         1148
Name: count, dtype: int64

=== CATEGORÍAS DE VENTA ===
Categoría_Venta
Retail       66240
Wholesale    14296
Name: count, dtype: int64

In [26]:
# ==========================================
# REVISIÓN DE FECHAS
# ==========================================

print("=== FECHAS DE VENTAS ===")

ventas["Fecha"] = pd.to_datetime(ventas["Fecha"], errors="coerce")

print(f"Fecha mínima: {ventas['Fecha'].min()}")
print(f"Fecha máxima: {ventas['Fecha'].max()}")

print("\nRegistros con fecha nula:")
print(ventas["Fecha"].isna().sum())

print("\nCantidad de ventas por año:")
print(ventas["Fecha"].dt.year.value_counts().sort_index())

=== FECHAS DE VENTAS ===
Fecha mínima: 2024-01-01 00:00:00
Fecha máxima: 2025-12-31 00:00:00

Registros con fecha nula:
0

Cantidad de ventas por año:
Fecha
2024    37583
2025    42953
Name: count, dtype: int64

In [27]:
# ==========================================
# REVISIÓN DE DEVOLUCIONES
# ==========================================

print("=== FECHAS DE DEVOLUCIONES ===")

devoluciones["Fecha"] = pd.to_datetime(
    devoluciones["Fecha"], 
    errors="coerce"
)

print(f"Fecha mínima: {devoluciones['Fecha'].min()}")
print(f"Fecha máxima: {devoluciones['Fecha'].max()}")

print("\nRegistros con fecha nula:")
print(devoluciones["Fecha"].isna().sum())

print("\nDevoluciones por año:")
print(devoluciones["Fecha"].dt.year.value_counts().sort_index())

=== FECHAS DE DEVOLUCIONES ===
Fecha mínima: 2024-01-02 00:00:00
Fecha máxima: 2026-11-01 00:00:00

Registros con fecha nula:
2797

Devoluciones por año:
Fecha
2024.0     780
2025.0    1047
2026.0      91
Name: count, dtype: int64

In [28]:
# ==========================================
# DIAGNÓSTICO DE FECHAS DE DEVOLUCIONES
# ==========================================

print("=== DEVOLUCIONES FUERA DEL PERÍODO 2024-2025 ===")

devoluciones_fuera_periodo = devoluciones[
    (devoluciones["Fecha"].dt.year < 2024) |
    (devoluciones["Fecha"].dt.year > 2025)
]

print(f"Registros fuera del período: {len(devoluciones_fuera_periodo)}")

print("\nPrimeros registros:")
display(devoluciones_fuera_periodo.head(20))

=== DEVOLUCIONES FUERA DEL PERÍODO 2024-2025 ===
Registros fuera del período: 91

Primeros registros:

,ID_Devolución,ID_Venta,Fecha,ID_Producto,ID_Cliente,ID_Tienda,Cantidad_Devuelta,Motivo,Precio_Unitario,Nombre_Cliente,Ubicación_Cliente,Nombre_Tienda,Ubicación_Tienda,Nombre_Producto,Categoría_Producto
4616,4617,78957,2026-01-01,59,170,21,2,No satisfecho,21.94,Sofía Pereira (170),ITALIA,Tienda Online IT,Italia,Conjunto Infantil,Ropa
4617,4618,79153,2026-01-01,60,640,20,2,Talle incorrecto,57.03,Lorenzo Ramírez,Brasil,Tienda Online BR,brasil,Remera Niño,Ropa
4618,4619,79345,2026-01-01,75,170,21,2,Defectuoso,28.30,Sofía Pereira (170),Italia,Tienda Online IT,Italia,Billetera,Ropa
4619,4620,79106,2026-01-01,56,205,8,3,Talle incorrecto,54.99,Gabriela Ferrari,Brasil,São Paulo Paulista,Brasil,Falda,Ropa
4620,4621,79429,2026-01-01,11,94,8,1,No satisfecho,917.18,María Ricci (94),Brasil,São Paulo Paulista,Brasil,"Tablet 10""",Electrónica
4621,4622,78574,2026-01-01,70,582,2,2,No satisfecho,15.20,Gabriela Castro (582),México,CDMX Santa Fe,MEXICO,Gorra,Ropa
4622,4623,78134,2026-01-01,13,565,17,1,No satisfecho,74.70,Grupo Castro Global,ITALIA,Bologna Maggiore,Italia,Parlante Portátil,Electrónica
4623,4624,78184,2026-01-01,1,141,1,1,Error en pedido,413.72,María Esposito,México,CDMX Polanco,Mexico,"Smart TV 43""",Electrónica
4624,4625,77027,2026-01-01,65,293,19,2,Defectuoso,143.53,Diego Costa (293),México,Tienda Online MX,México,Zapatillas Urbanas,Ropa
4625,4626,78229,2026-01-01,55,31,20,51,Defectuoso,69.00,Almacenes Torres Global,Brasil,Tienda Online BR,Brasil,Blusa,Ropa
4626,4627,79868,2026-01-01,54,486,20,3,No satisfecho,52.95,María Lima,Brasil,Tienda Online BR,Brasil,Campera Mujer,Ropa
4627,4628,79980,2026-02-01,71,522,3,3,Defectuoso,29.58,Jorge Santos,Mexico,Monterrey Centro,México,Cinturón,Ropa
4628,4629,78745,2026-02-01,19,575,12,1,No satisfecho,712.55,João Bianchi (575),Brasil,Porto Alegre Moinhos,Brazil,Smartwatch,Electrónica
4629,4630,78105,2026-02-01,66,53,8,2,Talle incorrecto,149.42,Mateo Ferrari (53),Brazil,São Paulo Paulista,Brasil,Botas,Ropa
4630,4631,77819,2026-02-01,5,206,17,1,No satisfecho,879.14,Luis Esposito (206),Italia,Bologna Maggiore,Italia,"Smart TV 75""",Electrónica
4631,4632,78975,2026-02-01,19,227,15,1,No satisfecho,712.55,Beatriz Rossi (227),Italia,Roma Termini,Italia,Smartwatch,Electrónica
4632,4633,75591,2026-02-01,69,445,3,1,Talle incorrecto,97.74,Giulia Russo,México,Monterrey Centro,MEXICO,Ojotas,Ropa
4633,4634,79726,2026-02-01,75,390,21,2,No satisfecho,28.30,Valeria Costa,Italia,Tienda Online IT,Italia,Billetera,ropa
4634,4635,79737,2026-02-01,62,511,15,2,Talle incorrecto,62.71,Beatriz Costa (511),Italy,Roma Termini,ITALIA,Campera Niño,Ropa
4635,4636,80019,2026-02-01,62,571,11,2,No satisfecho,62.71,Luis Hernández (571),Brazil,Belo Horizonte Savassi,Brasil,Campera Niño,Ropa

In [29]:
print("=== DEVOLUCIONES CON FECHA NULA ===")

devoluciones_nulas = devoluciones[
    devoluciones["Fecha"].isna()
]

print(f"Registros con fecha nula: {len(devoluciones_nulas)}")

display(devoluciones_nulas.head(20))

=== DEVOLUCIONES CON FECHA NULA ===
Registros con fecha nula: 2797

,ID_Devolución,ID_Venta,Fecha,ID_Producto,ID_Cliente,ID_Tienda,Cantidad_Devuelta,Motivo,Precio_Unitario,Nombre_Cliente,Ubicación_Cliente,Nombre_Tienda,Ubicación_Tienda,Nombre_Producto,Categoría_Producto
23,24,197,NaT,5,514,5,2,Defectuoso,763.49,Mayorista Costa del Norte,MEXICO,Puebla Angelópolis,México,"Smart TV 75""",Electrónica
24,25,440,NaT,67,639,8,1,Error en pedido,81.99,Beatriz Ferrari (639),Brasil,São Paulo Paulista,Brasil,Sandalias,Ropa
25,26,742,NaT,55,548,6,2,Talle incorrecto,60.66,Andrés Santos,MEXICO,Querétaro Juriquilla,México,Blusa,Ropa
26,27,387,NaT,101,105,7,1,Error en pedido,6.31,Gabriela Souza (105),Mexico,Mérida Altabrisa,México,Papel Higiénico x12,Alimentos
27,28,756,NaT,67,430,8,3,No satisfecho,81.99,Jorge Ramírez (430),brasil,São Paulo Paulista,Brazil,Sandalias,Ropa
28,29,850,NaT,74,390,14,1,No satisfecho,35.87,Valeria Costa,Italia,Milano Duomo,Italia,Lentes de Sol,Ropa
29,30,927,NaT,3,110,15,2,Defectuoso,1036.30,Thiago Pereira (110),Italia,Roma Termini,Italia,"Smart TV 55""",Electrónica
30,31,812,NaT,5,134,2,1,No satisfecho,850.19,Pedro Ricci (134),México,CDMX Santa Fe,México,"Smart TV 75""",Electrónica
31,32,717,NaT,22,302,18,1,Defectuoso,14.61,Ana Silva (302),Italia,Napoli Toledo,Italia,Cable HDMI,Electrónica
32,33,1166,NaT,60,335,14,3,No satisfecho,46.31,Lorenzo Oliveira,Italia,Milano Duomo,Italia,Remera Niño,Ropa
33,34,1013,NaT,59,495,14,2,Talle incorrecto,17.92,Paula Lima (495),Italia,Milano Duomo,Italia,Conjunto Infantil,Ropa
34,35,854,NaT,71,110,15,1,Talle incorrecto,20.97,Thiago Pereira (110),Italia,Roma Termini,Italia,Cinturón,Ropa
35,36,679,NaT,32,265,9,3,Defectuoso,226.21,Comercial Silva Global,Brasil,São Paulo Morumbi,Brasil,Sillón Reclinable,Muebles
36,37,755,NaT,17,55,20,1,Llegó dañado,401.38,Jorge Russo (55),Brazil,Tienda Online BR,Brasil,Smartphone Gama Media,Electrónica
37,38,464,NaT,11,619,15,1,Defectuoso,854.46,Beatriz López,Italia,Roma Termini,Italia,"Tablet 10""",Electronica
38,39,718,NaT,3,523,17,1,Defectuoso,1036.30,Andrés Bianchi,Italia,Bologna Maggiore,Italia,"Smart TV 55""",Electrónica
39,40,1163,NaT,17,592,8,1,Defectuoso,401.38,Carlos Santos (592),brasil,São Paulo Paulista,Brasil,Smartphone Gama Media,Electrónica
40,41,648,NaT,66,192,17,2,Defectuoso,101.39,Sofía Lima (192),Italy,Bologna Maggiore,Italia,Botas,Ropa
41,42,1057,NaT,20,290,10,2,No satisfecho,509.96,Comercial Russo Atlántica,Brasil,Rio Barra,Brasil,Smartphone Gama Baja,Electrónica
42,43,548,NaT,5,430,10,1,Defectuoso,850.19,Jorge Ramírez (430),Brasil,Rio Barra,Brazil,"Smart TV 75""",Electrónica

In [30]:
print("=== CALIDAD DE FECHAS EN DEVOLUCIONES ===")

total_devoluciones = len(devoluciones)

fechas_nulas = devoluciones["Fecha"].isna().sum()

fechas_validas = devoluciones["Fecha"].notna().sum()

print(f"Total de devoluciones: {total_devoluciones:,}")
print(f"Fechas nulas: {fechas_nulas:,}")
print(f"Fechas válidas: {fechas_validas:,}")
print(f"% de fechas nulas: {(fechas_nulas / total_devoluciones) * 100:.2f}%")

=== CALIDAD DE FECHAS EN DEVOLUCIONES ===
Total de devoluciones: 4,715
Fechas nulas: 2,797
Fechas válidas: 1,918
% de fechas nulas: 59.32%

In [31]:
print("=== DEVOLUCIONES CON FECHA NULA ===")

devoluciones_fecha_nula = devoluciones[
    devoluciones["Fecha"].isna()
]

print(f"Cantidad de registros: {len(devoluciones_fecha_nula):,}")

display(
    devoluciones_fecha_nula.head(20)
)

=== DEVOLUCIONES CON FECHA NULA ===
Cantidad de registros: 2,797

,ID_Devolución,ID_Venta,Fecha,ID_Producto,ID_Cliente,ID_Tienda,Cantidad_Devuelta,Motivo,Precio_Unitario,Nombre_Cliente,Ubicación_Cliente,Nombre_Tienda,Ubicación_Tienda,Nombre_Producto,Categoría_Producto
23,24,197,NaT,5,514,5,2,Defectuoso,763.49,Mayorista Costa del Norte,MEXICO,Puebla Angelópolis,México,"Smart TV 75""",Electrónica
24,25,440,NaT,67,639,8,1,Error en pedido,81.99,Beatriz Ferrari (639),Brasil,São Paulo Paulista,Brasil,Sandalias,Ropa
25,26,742,NaT,55,548,6,2,Talle incorrecto,60.66,Andrés Santos,MEXICO,Querétaro Juriquilla,México,Blusa,Ropa
26,27,387,NaT,101,105,7,1,Error en pedido,6.31,Gabriela Souza (105),Mexico,Mérida Altabrisa,México,Papel Higiénico x12,Alimentos
27,28,756,NaT,67,430,8,3,No satisfecho,81.99,Jorge Ramírez (430),brasil,São Paulo Paulista,Brazil,Sandalias,Ropa
28,29,850,NaT,74,390,14,1,No satisfecho,35.87,Valeria Costa,Italia,Milano Duomo,Italia,Lentes de Sol,Ropa
29,30,927,NaT,3,110,15,2,Defectuoso,1036.30,Thiago Pereira (110),Italia,Roma Termini,Italia,"Smart TV 55""",Electrónica
30,31,812,NaT,5,134,2,1,No satisfecho,850.19,Pedro Ricci (134),México,CDMX Santa Fe,México,"Smart TV 75""",Electrónica
31,32,717,NaT,22,302,18,1,Defectuoso,14.61,Ana Silva (302),Italia,Napoli Toledo,Italia,Cable HDMI,Electrónica
32,33,1166,NaT,60,335,14,3,No satisfecho,46.31,Lorenzo Oliveira,Italia,Milano Duomo,Italia,Remera Niño,Ropa
33,34,1013,NaT,59,495,14,2,Talle incorrecto,17.92,Paula Lima (495),Italia,Milano Duomo,Italia,Conjunto Infantil,Ropa
34,35,854,NaT,71,110,15,1,Talle incorrecto,20.97,Thiago Pereira (110),Italia,Roma Termini,Italia,Cinturón,Ropa
35,36,679,NaT,32,265,9,3,Defectuoso,226.21,Comercial Silva Global,Brasil,São Paulo Morumbi,Brasil,Sillón Reclinable,Muebles
36,37,755,NaT,17,55,20,1,Llegó dañado,401.38,Jorge Russo (55),Brazil,Tienda Online BR,Brasil,Smartphone Gama Media,Electrónica
37,38,464,NaT,11,619,15,1,Defectuoso,854.46,Beatriz López,Italia,Roma Termini,Italia,"Tablet 10""",Electronica
38,39,718,NaT,3,523,17,1,Defectuoso,1036.30,Andrés Bianchi,Italia,Bologna Maggiore,Italia,"Smart TV 55""",Electrónica
39,40,1163,NaT,17,592,8,1,Defectuoso,401.38,Carlos Santos (592),brasil,São Paulo Paulista,Brasil,Smartphone Gama Media,Electrónica
40,41,648,NaT,66,192,17,2,Defectuoso,101.39,Sofía Lima (192),Italy,Bologna Maggiore,Italia,Botas,Ropa
41,42,1057,NaT,20,290,10,2,No satisfecho,509.96,Comercial Russo Atlántica,Brasil,Rio Barra,Brasil,Smartphone Gama Baja,Electrónica
42,43,548,NaT,5,430,10,1,Defectuoso,850.19,Jorge Ramírez (430),Brasil,Rio Barra,Brazil,"Smart TV 75""",Electrónica

In [32]:
print("=== RANGO Y CALIDAD DE FECHAS EN DEVOLUCIONES ===")

print("Fecha mínima:", devoluciones["Fecha"].min())
print("Fecha máxima:", devoluciones["Fecha"].max())

print("\nCantidad de fechas posteriores a 2025-12-31:")

fechas_futuras = devoluciones[
    devoluciones["Fecha"] > pd.Timestamp("2025-12-31")
]

print(len(fechas_futuras))

=== RANGO Y CALIDAD DE FECHAS EN DEVOLUCIONES ===
Fecha mínima: 2024-01-02 00:00:00
Fecha máxima: 2026-11-01 00:00:00

Cantidad de fechas posteriores a 2025-12-31:
91

In [33]:
print("=== DEVOLUCIONES FUERA DEL PERÍODO DEL CHALLENGE ===")

devoluciones_fuera_periodo = devoluciones[
    devoluciones["Fecha"] > pd.Timestamp("2025-12-31")
]

print(f"Cantidad de registros: {len(devoluciones_fuera_periodo):,}")

display(
    devoluciones_fuera_periodo[
        [
            "ID_Devolución",
            "ID_Venta",
            "Fecha",
            "ID_Producto",
            "Cantidad_Devuelta",
            "Motivo",
            "Precio_Unitario"
        ]
    ].sort_values("Fecha").head(20)
)

=== DEVOLUCIONES FUERA DEL PERÍODO DEL CHALLENGE ===
Cantidad de registros: 91

,ID_Devolución,ID_Venta,Fecha,ID_Producto,Cantidad_Devuelta,Motivo,Precio_Unitario
4616,4617,78957,2026-01-01,59,2,No satisfecho,21.94
4626,4627,79868,2026-01-01,54,3,No satisfecho,52.95
4625,4626,78229,2026-01-01,55,51,Defectuoso,69.00
4623,4624,78184,2026-01-01,1,1,Error en pedido,413.72
4622,4623,78134,2026-01-01,13,1,No satisfecho,74.70
4624,4625,77027,2026-01-01,65,2,Defectuoso,143.53
4620,4621,79429,2026-01-01,11,1,No satisfecho,917.18
4619,4620,79106,2026-01-01,56,3,Talle incorrecto,54.99
4618,4619,79345,2026-01-01,75,2,Defectuoso,28.30
4617,4618,79153,2026-01-01,60,2,Talle incorrecto,57.03
4621,4622,78574,2026-01-01,70,2,No satisfecho,15.20
4634,4635,79737,2026-02-01,62,2,Talle incorrecto,62.71
4638,4639,78542,2026-02-01,55,2,Error en pedido,83.25
4637,4638,75198,2026-02-01,15,1,Defectuoso,98.20
4636,4637,78871,2026-02-01,65,1,Talle incorrecto,143.53
4635,4636,80019,2026-02-01,62,2,No satisfecho,62.71
4633,4634,79726,2026-02-01,75,2,No satisfecho,28.30
4629,4630,78105,2026-02-01,66,2,Talle incorrecto,149.42
4631,4632,78975,2026-02-01,19,1,No satisfecho,712.55
4630,4631,77819,2026-02-01,5,1,No satisfecho,879.14

In [35]:
print("=== DEVOLUCIONES CON FECHA NULA Y FECHA DE VENTA DISPONIBLE ===")

devoluciones_fecha_nula = devoluciones[
    devoluciones["Fecha"].isna()
].copy()

devoluciones_fecha_nula["Fecha_Venta"] = devoluciones_fecha_nula["ID_Venta"].map(
    ventas.set_index("ID_Venta")["Fecha"]
)

print(f"Devoluciones con fecha nula: {len(devoluciones_fecha_nula):,}")
print(
    f"Devoluciones con fecha de venta disponible: "
    f"{devoluciones_fecha_nula['Fecha_Venta'].notna().sum():,}"
)
print(
    f"Devoluciones sin fecha de venta disponible: "
    f"{devoluciones_fecha_nula['Fecha_Venta'].isna().sum():,}"
)

display(
    devoluciones_fecha_nula[
        [
            "ID_Devolución",
            "ID_Venta",
            "Fecha",
            "Fecha_Venta",
            "ID_Producto",
            "Cantidad_Devuelta",
            "Motivo"
        ]
    ].head(20)
)

=== DEVOLUCIONES CON FECHA NULA Y FECHA DE VENTA DISPONIBLE ===

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

In [36]:
print("=== DUPLICADOS DE ID_VENTA EN VENTAS ===")

duplicados_id_venta = ventas[
    ventas["ID_Venta"].duplicated(keep=False)
].sort_values("ID_Venta")

print(f"Registros involucrados en IDs de venta duplicados: {len(duplicados_id_venta):,}")
print(f"IDs de venta duplicados: {duplicados_id_venta['ID_Venta'].nunique():,}")

display(
    duplicados_id_venta[
        [
            "ID_Venta",
            "Fecha",
            "ID_Producto",
            "ID_Cliente",
            "ID_Tienda",
            "Cantidad",
            "Precio_Unitario"
        ]
    ].head(20)
)

=== DUPLICADOS DE ID_VENTA EN VENTAS ===
Registros involucrados en IDs de venta duplicados: 482
IDs de venta duplicados: 241

,ID_Venta,Fecha,ID_Producto,ID_Cliente,ID_Tienda,Cantidad,Precio_Unitario
1086,1087,2024-01-14,75,608,8,10,17.53
1087,1087,2024-01-14,75,608,8,10,17.53
1328,1328,2024-01-18,5,514,5,5,748.77
1329,1328,2024-01-18,5,514,5,5,748.77
1782,1781,2024-01-23,52,302,18,2,67.90
1783,1781,2024-01-23,52,302,18,2,67.90
1960,1958,2024-01-26,55,514,1,23,53.97
1961,1958,2024-01-26,55,514,1,23,53.97
2469,2466,2024-02-01,15,402,11,2,74.35
2470,2466,2024-02-01,15,402,11,2,74.35
2801,2797,2024-02-05,17,301,12,2,347.33
2802,2797,2024-02-05,17,301,12,2,347.33
2830,2825,2024-02-06,89,12,1,61,5.75
2831,2825,2024-02-06,89,12,1,61,5.75
3720,3714,2024-02-17,85,608,8,109,9.03
3721,3714,2024-02-17,85,608,8,109,9.03
4010,4003,2024-02-21,78,196,2,4,6.00
4011,4003,2024-02-21,78,196,2,4,6.00
4298,4290,2024-02-24,55,529,8,2,60.66
4299,4290,2024-02-24,55,529,8,2,60.66

In [37]:
print("=== VALIDACIÓN DE DUPLICADOS DE ID_VENTA ===")

ventas_duplicadas = ventas[
    ventas["ID_Venta"].duplicated(keep=False)
].sort_values("ID_Venta")

print(f"Registros involucrados: {len(ventas_duplicadas):,}")
print(f"IDs de venta duplicados: {ventas_duplicadas['ID_Venta'].nunique():,}")

print("\n¿Los duplicados tienen la misma fecha de venta?")

conflictos_fecha = (
    ventas_duplicadas
    .groupby("ID_Venta")["Fecha"]
    .nunique()
)

print(
    f"IDs duplicados con fechas diferentes: "
    f"{(conflictos_fecha > 1).sum():,}"
)

=== VALIDACIÓN DE DUPLICADOS DE ID_VENTA ===
Registros involucrados: 482
IDs de venta duplicados: 241

¿Los duplicados tienen la misma fecha de venta?
IDs duplicados con fechas diferentes: 0

In [38]:
print("=== DUPLICADOS EXACTOS EN VENTAS ===")

columnas_ventas = ventas.columns.tolist()

duplicados_exactos = ventas[
    ventas.duplicated(subset=columnas_ventas, keep=False)
]

print(f"Registros duplicados exactos: {len(duplicados_exactos):,}")
print(
    f"IDs de venta afectados: "
    f"{duplicados_exactos['ID_Venta'].nunique():,}"
)

=== DUPLICADOS EXACTOS EN VENTAS ===
Registros duplicados exactos: 482
IDs de venta afectados: 241

In [39]:
print("=== DEVOLUCIONES 2026 Y FECHA DE LA VENTA ===")

devoluciones_2026 = devoluciones[
    devoluciones["Fecha"] > pd.Timestamp("2025-12-31")
].copy()

devoluciones_2026["Fecha_Venta"] = devoluciones_2026["ID_Venta"].map(
    ventas.drop_duplicates("ID_Venta").set_index("ID_Venta")["Fecha"]
)

print(f"Devoluciones posteriores a 2025: {len(devoluciones_2026):,}")

print("\nFecha de venta:")
print(devoluciones_2026["Fecha_Venta"].describe())

print("\nDevoluciones 2026 cuya venta pertenece a 2024-2025:")

ventas_periodo = devoluciones_2026[
    devoluciones_2026["Fecha_Venta"] <= pd.Timestamp("2025-12-31")
]

print(f"{len(ventas_periodo):,}")

=== DEVOLUCIONES 2026 Y FECHA DE LA VENTA ===
Devoluciones posteriores a 2025: 91

Fecha de venta:
count                            91
mean     2025-12-24 13:42:51.428571
min             2025-12-03 00:00:00
25%             2025-12-22 00:00:00
50%             2025-12-27 00:00:00
75%             2025-12-29 00:00:00
max             2025-12-31 00:00:00
Name: Fecha_Venta, dtype: object

Devoluciones 2026 cuya venta pertenece a 2024-2025:
91

In [40]:
print("=== VALORES NULOS ===")

for nombre, df in {
    "Ventas": ventas,
    "Devoluciones": devoluciones,
    "Precios": precios,
    "Costos": costos,
    "Objetivos": objetivos
}.items():

    nulos = df.isna().sum()
    nulos = nulos[nulos > 0]

    print(f"\n--- {nombre} ---")

    if len(nulos) == 0:
        print("Sin valores nulos.")
    else:
        print(nulos)

=== VALORES NULOS ===

--- Ventas ---
Canal_Venta    340
dtype: int64

--- Devoluciones ---
Fecha    2797
dtype: int64

--- Precios ---
Sin valores nulos.

--- Costos ---
Sin valores nulos.

--- Objetivos ---
Sin valores nulos.

In [41]:
# ==========================================
# INTEGRIDAD: DEVOLUCIONES VS VENTAS
# ==========================================

ids_ventas = set(ventas["ID_Venta"])

devoluciones_sin_venta = devoluciones[
    ~devoluciones["ID_Venta"].isin(ids_ventas)
]

print("=== DEVOLUCIONES SIN VENTA ASOCIADA ===")
print(f"Total: {len(devoluciones_sin_venta):,}")

display(
    devoluciones_sin_venta[
        ["ID_Devolución", "ID_Venta", "Fecha", "ID_Producto", "Cantidad_Devuelta"]
    ].head(20)
)

=== DEVOLUCIONES SIN VENTA ASOCIADA ===
Total: 12

      ID_Devolución  ID_Venta      Fecha  ID_Producto  Cantidad_Devuelta
151             152    901989        NaT           71                  2
378             379    906819 2024-04-04           22                  2
526             527    909784 2024-03-05           66                  3
868             869    916626 2024-08-07           59                  2
1007           1008    918264        NaT           62                  1
1248           1249    923111 2024-09-09           21                  1
1426           1427    925136 2024-12-10           46                 11
1535           1536    927892 2024-01-11            3                  1
2608           2609    944886 2025-09-04           24                  1
3583           3584    962237 2025-02-09           53                  3
3671           3672    964365        NaT           97                 29
3745           3746    964968        NaT           20                 10

In [42]:
# ==========================================
# RANGOS Y VALORES ANÓMALOS
# ==========================================

print("=== VENTAS ===")
print("Cantidad mínima:", ventas["Cantidad"].min())
print("Cantidad máxima:", ventas["Cantidad"].max())
print("Precio mínimo:", ventas["Precio_Unitario"].min())
print("Precio máximo:", ventas["Precio_Unitario"].max())

print("\n=== DEVOLUCIONES ===")
print("Cantidad devuelta mínima:", devoluciones["Cantidad_Devuelta"].min())
print("Cantidad devuelta máxima:", devoluciones["Cantidad_Devuelta"].max())
print("Precio mínimo:", devoluciones["Precio_Unitario"].min())
print("Precio máximo:", devoluciones["Precio_Unitario"].max())

print("\n=== COSTOS ===")
costo_num = pd.to_numeric(
    costos["Costo_Unitario"].astype(str).str.replace(",", ".", regex=False),
    errors="coerce"
)

print("Costo mínimo:", costo_num.min())
print("Costo máximo:", costo_num.max())

print("\n=== CEROS Y NEGATIVOS ===")
print("Ventas - cantidades <= 0:", (ventas["Cantidad"] <= 0).sum())
print("Ventas - precios <= 0:", (ventas["Precio_Unitario"] <= 0).sum())
print("Devoluciones - cantidades <= 0:", (devoluciones["Cantidad_Devuelta"] <= 0).sum())
print("Devoluciones - precios <= 0:", (devoluciones["Precio_Unitario"] <= 0).sum())
print("Costos - costos <= 0:", (costo_num <= 0).sum())

=== VENTAS ===
Cantidad mínima: 1
Cantidad máxima: 8000
Precio mínimo: 2.36
Precio máximo: 1440.89

=== DEVOLUCIONES ===
Cantidad devuelta mínima: 1
Cantidad devuelta máxima: 222
Precio mínimo: 2.74
Precio máximo: 1440.89

=== COSTOS ===
Costo mínimo: 2.2
Costo máximo: 931.4

=== CEROS Y NEGATIVOS ===
Ventas - cantidades <= 0: 0
Ventas - precios <= 0: 0
Devoluciones - cantidades <= 0: 0
Devoluciones - precios <= 0: 0
Costos - costos <= 0: 0